Integrated project opener from `plugin-utilities`
JetBrains-Research/psiminer pull request #15
Opened 2021-08-16 07:18 UTC by Furetur

2021-08-16 09:34 UTC, SpirinEgor requested changes

2021-08-16 09:34 UTC, SpirinEgor commented on README.md
> +## Additional preprocessing
Это бы в docs положить. Здесь оставить предложение, про то зачем это и в конце ссылку на доп детали. Не хочется увеличивать ридми просто.

2021-08-16 09:34 UTC, SpirinEgor commented on README.md
> +PSIMiner can perform additional preprocessing increasing the changes that projects in the dataset are opened correctly by IDEA.
1. `PSIMiner` -- используй кавычки
2. "changes" -- может ты имел ввиду chances?

2021-08-16 09:34 UTC, SpirinEgor commented on psiminer-cli/build.gradle.kts
> +    implementation("org.apache.logging.log4j:log4j-core:2.14.1")
Логгирование уже и так есть, оно из идеи идет. И даже настроено. Не надо ничего подключать, смотри plugin runner для примера.

2021-08-16 09:34 UTC, SpirinEgor commented on psiminer-cli/src/main/kotlin/PluginRunner.kt
> +            repositoryOpener = getKotlinJavaRepositoryOpener(),
Это должно быть частью pipeline

2021-08-16 09:34 UTC, SpirinEgor commented on psiminer-cli/src/main/kotlin/config/Config.kt
> +        }
```
fun createPreprocessorManager(): PreprocessorManager? =
    if (enable) getKotlinJavaPreprocessorManager(androidSdkHome) else null
```

2021-08-16 09:34 UTC, SpirinEgor commented on psiminer-core/src/main/kotlin/Pipeline.kt
> -        val project = openProject(projectFile) ?: return
Там в конце еще есть закрытие и диспоуз проекта, его поди тоже надо убрать

2021-08-16 09:34 UTC, SpirinEgor commented on settings.gradle.kts
> +val utilitiesProjectName = "org.jetbrains.research.pluginUtilities"
Мне не нравится, что ты это пишешь и тут, и в `build.gradle.kts`

2021-08-16 09:34 UTC, SpirinEgor commented on settings.gradle.kts
> +pluginManagement {
в `build.gradle.kts` уже есть список репозиториев, зачем дублировать

2021-08-16 11:23 UTC, Furetur commented on settings.gradle.kts
> +pluginManagement {
Я думал он нужен, а оказывается можно убрать

2021-08-16 13:04 UTC, SpirinEgor commented on psiminer-cli/src/main/kotlin/config/Config.kt
> +    ),
Немного не нравится рефакторинг здесь :)
```
@SerialName("additional preprocessing") val additionalPreprocessing: PreprocessingConfig
    = PreprocessingConfig(enable = false),

2021-08-16 13:04 UTC, SpirinEgor commented on settings.gradle.kts
> +}
А пустую строчку в конце файла? :)

2021-08-17 07:05 UTC, Furetur commented on settings.gradle.kts
> +}
Она вроде бы есть, гитхаб же не показывает "⛔︎". Ну локально она у меня есть :)

2021-08-19 08:33 UTC, SpirinEgor approved these changes

2021-08-19 08:33 UTC, merged