Php control flow
JetBrains-Research/psiminer pull request #39
Opened 2023-01-11 16:43 UTC by max-martynov

2023-01-16 21:33 UTC, egor-bogomolov requested changes
Nice work! 🚀 
There are a few minor comments and suggestions. Other than that, let's figure out a way how to write tests effectively, so we do not have to write lots of random strings as test answers 🥲

2023-01-16 21:33 UTC, egor-bogomolov commented on psiminer-core/src/main/kotlin/psi/graphs/edgeProviders/php/PhpControlFlowEdgeProvider.kt
> +            nextInstructions[index].forEach { toIndex ->
Let's rename the variable to highlight that the next instruction will be non-branching

2023-01-16 21:33 UTC, egor-bogomolov commented on psiminer-core/src/main/kotlin/psi/graphs/edgeProviders/php/PhpControlFlowEdgeProvider.kt
> +                newEdges.add(Edge(element, toElement, edgeType))
You can remove the edgeType variable here and substitute the actual type. It will be a bit more readable.

2023-01-16 21:33 UTC, egor-bogomolov commented on psiminer-core/src/test/kotlin/psi/graphs/edgeProviders/php/PhpControlFlowEdgeProviderTest.kt
> +            println(textRepresentation)
Let's discuss how to make test writing easier in our case 😸

2023-01-18 15:09 UTC, max-martynov commented on psiminer-core/src/main/kotlin/psi/assignment/PhpAssignmentProvider.kt
> +        }
Yeah this code looks really strange...
Replaced it with [filterIsInstance](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/filter-is-instance.html), I think it's even more accurate.

2023-01-18 15:39 UTC, max-martynov commented on psiminer-core/src/main/kotlin/psi/assignment/PhpAssignmentProvider.kt
>      }
At first I thought no but after your comment I found that statements like the one below are possible:
```php
$a = $b = $c = $d = array();
```
According to the PsiViewer it forms a hierarchy of AssignmentExpressions so my new implementation should work fine.

2023-01-18 15:42 UTC, max-martynov commented on psiminer-core/src/main/kotlin/psi/graphs/edgeProviders/php/PhpControlFlowEdgeProvider.kt
> +        println(instruction.toString() + "  " + instruction.anchor + "  " + instruction.predecessors.joinToString(" "))
Oops forgot to delete this line actually 🙃
But anyway thanks for the tip

2023-01-24 20:09 UTC, egor-bogomolov commented on psiminer-core/src/main/kotlin/psi/assignment/PhpAssignmentProvider.kt
>      }
And what about cases like this:
```php
$a = array($b, $c, $d)
```

I believe that it is a valid PHP code (please correct me if I am wrong) 🤔

2023-01-26 10:24 UTC, egor-bogomolov approved these changes
Now it looks great, thank you very much! 🚀

2023-01-26 16:24 UTC, merged